name: ğŸ§ª Run PHP tests

on:
  push:
    branches: 
      - main
    # paths: 
    #   - users-management/**
    
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./users-management

    steps:    
      - name: ğŸ“‚ Checkout
        uses: actions/checkout@v3

      - name: ğŸ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_pgsql
          coverage: none

      - name: â¬ Install dependencies
        run: composer install -n --prefer-dist

      - name: ğŸ Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: âœ… Run tests
        run: php artisan test